### ISSUE TITLE
USPS Stamp Link broken

### ISSUE THREAD

**Issue by garrett-lane** [hackclub/mail-team#1]
Goes to an unknown page on Amazon. Figured I would let you know.

**Comment by zachlatta** [comment]
Same problem. GIF:

![2020-01-21 09 14 54](https://user-images.githubusercontent.com/992248/72826881-88d45380-3c2e-11ea-9ead-e6187fcc77df.gif)

**Comment by iamcpdev** [comment]
Fixed!
